### ISSUE TITLE
AX

### ISSUE THREAD

**Issue by ThanushiyaMary** [abc-software-solution/AB#2]
[AB-master.zip](https://github.com/abc-software-solution/AB/files/2859622/AB-master.zip)ScLOSED

**Comment by Madhuyayathi** [comment]
[AB-master.zip](https://github.com/abc-software-solution/AB/files/2859634/AB-master.zip)

**Comment by ThanushiyaMary** [comment]
[AB-master.zip](https://github.com/abc-software-solution/AB/files/2859648/AB-master.zip)
ok
